export const teamBgClassMap: Record<string, string> = {
  "Arsenal": "bg-red-400",
  "Aston Villa": "bg-purple-400",
  "Bournemouth": "bg-red-400",
  "Brentford": "bg-red-300",
  "Brighton": "bg-blue-400",
  "Burnley": "bg-rose-400",
  "Chelsea": "bg-blue-400",
  "Crystal Palace": "bg-blue-400",
  "Everton": "bg-blue-400",
  "Fulham": "bg-gray-400",
  "Ipswich": "bg-blue-400",
  "Leeds": "bg-yellow-200",
  "Leicester": "bg-blue-300",
  "Liverpool": "bg-red-500",
  "Man City": "bg-sky-400",
  "Man United": "bg-red-700",
  "Newcastle": "bg-black-600",
  "Nott'm Forest": "bg-red-600",
  "Southampton": "bg-red-500",
  "Sunderland": "bg-red-600",
  "Tottenham": "bg-neutral-200",
  "West Ham": "bg-pink-700",
  "Wolves": "bg-yellow-500"
};
